name: Deploy to GitHub Pages

# When should this workflow run?
on:
  push:
    branches: [ main ]  # Triggers on pushes to main branch
  pull_request:
    branches: [ main ]  # Also runs on PRs to main for testing

# Set permissions needed for GitHub Pages deployment
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Build job - prepare the site for deployment
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Get the code from the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up GitHub Pages configuration
      - name: Setup Pages
        uses: actions/configure-pages@v4

      # Step 3: Upload the built site as an artifact
      # For now, we're just uploading the HTML directly
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'  # Upload entire repository (contains our index.html)

  # Deploy job - actually publish to GitHub Pages
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build  # This job depends on the build job completing
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4